// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.yflog.lckmgr.msg;

public final class LSMessage {
  private LSMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.yflog.lckmgr.msg.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 1;</code>
     */
    OK(0, 1),
    /**
     * <code>INVALID_LOCK = 2;</code>
     */
    INVALID_LOCK(1, 2),
    /**
     * <code>TIME_OUT = 3;</code>
     */
    TIME_OUT(2, 3),
    /**
     * <code>CLIENT_CLOSED = 4;</code>
     */
    CLIENT_CLOSED(3, 4),
    /**
     * <code>NOT_LOCK_OWNER = 6;</code>
     */
    NOT_LOCK_OWNER(4, 6),
    ;

    /**
     * <code>OK = 1;</code>
     */
    public static final int OK_VALUE = 1;
    /**
     * <code>INVALID_LOCK = 2;</code>
     */
    public static final int INVALID_LOCK_VALUE = 2;
    /**
     * <code>TIME_OUT = 3;</code>
     */
    public static final int TIME_OUT_VALUE = 3;
    /**
     * <code>CLIENT_CLOSED = 4;</code>
     */
    public static final int CLIENT_CLOSED_VALUE = 4;
    /**
     * <code>NOT_LOCK_OWNER = 6;</code>
     */
    public static final int NOT_LOCK_OWNER_VALUE = 6;


    public final int getNumber() { return value; }

    public static Status valueOf(int value) {
      switch (value) {
        case 1: return OK;
        case 2: return INVALID_LOCK;
        case 3: return TIME_OUT;
        case 4: return CLIENT_CLOSED;
        case 6: return NOT_LOCK_OWNER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.yflog.lckmgr.msg.LSMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Status(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.yflog.lckmgr.msg.Status)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yflog.lckmgr.msg.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.yflog.lckmgr.msg.Message.Command command = 1 [default = ACQUIRE];</code>
     *
     * <pre>
     * header part
     * </pre>
     */
    boolean hasCommand();
    /**
     * <code>required .com.yflog.lckmgr.msg.Message.Command command = 1 [default = ACQUIRE];</code>
     *
     * <pre>
     * header part
     * </pre>
     */
    com.yflog.lckmgr.msg.LSMessage.Message.Command getCommand();

    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     * an uuid string
     * </pre>
     */
    boolean hasClientId();
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     * an uuid string
     * </pre>
     */
    java.lang.String getClientId();
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     * an uuid string
     * </pre>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>required int64 seqId = 3;</code>
     */
    boolean hasSeqId();
    /**
     * <code>required int64 seqId = 3;</code>
     */
    long getSeqId();

    /**
     * <code>optional .com.yflog.lckmgr.msg.Status status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .com.yflog.lckmgr.msg.Status status = 4;</code>
     */
    com.yflog.lckmgr.msg.LSMessage.Status getStatus();

    /**
     * <code>optional string errmsg = 5;</code>
     */
    boolean hasErrmsg();
    /**
     * <code>optional string errmsg = 5;</code>
     */
    java.lang.String getErrmsg();
    /**
     * <code>optional string errmsg = 5;</code>
     */
    com.google.protobuf.ByteString
        getErrmsgBytes();

    /**
     * <code>optional string lckName = 6;</code>
     */
    boolean hasLckName();
    /**
     * <code>optional string lckName = 6;</code>
     */
    java.lang.String getLckName();
    /**
     * <code>optional string lckName = 6;</code>
     */
    com.google.protobuf.ByteString
        getLckNameBytes();
  }
  /**
   * Protobuf type {@code com.yflog.lckmgr.msg.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.yflog.lckmgr.msg.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.yflog.lckmgr.msg.LSMessage.Message.Command value = com.yflog.lckmgr.msg.LSMessage.Message.Command.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                command_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              clientId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              seqId_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.yflog.lckmgr.msg.LSMessage.Status value = com.yflog.lckmgr.msg.LSMessage.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                status_ = value;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              errmsg_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              lckName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yflog.lckmgr.msg.LSMessage.internal_static_com_yflog_lckmgr_msg_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yflog.lckmgr.msg.LSMessage.internal_static_com_yflog_lckmgr_msg_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yflog.lckmgr.msg.LSMessage.Message.class, com.yflog.lckmgr.msg.LSMessage.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.yflog.lckmgr.msg.Message.Command}
     */
    public enum Command
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACQUIRE = 1;</code>
       */
      ACQUIRE(0, 1),
      /**
       * <code>RELEASE = 2;</code>
       */
      RELEASE(1, 2),
      ;

      /**
       * <code>ACQUIRE = 1;</code>
       */
      public static final int ACQUIRE_VALUE = 1;
      /**
       * <code>RELEASE = 2;</code>
       */
      public static final int RELEASE_VALUE = 2;


      public final int getNumber() { return value; }

      public static Command valueOf(int value) {
        switch (value) {
          case 1: return ACQUIRE;
          case 2: return RELEASE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yflog.lckmgr.msg.LSMessage.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Command[] VALUES = values();

      public static Command valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Command(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.yflog.lckmgr.msg.Message.Command)
    }

    private int bitField0_;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private com.yflog.lckmgr.msg.LSMessage.Message.Command command_;
    /**
     * <code>required .com.yflog.lckmgr.msg.Message.Command command = 1 [default = ACQUIRE];</code>
     *
     * <pre>
     * header part
     * </pre>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.yflog.lckmgr.msg.Message.Command command = 1 [default = ACQUIRE];</code>
     *
     * <pre>
     * header part
     * </pre>
     */
    public com.yflog.lckmgr.msg.LSMessage.Message.Command getCommand() {
      return command_;
    }

    public static final int CLIENTID_FIELD_NUMBER = 2;
    private java.lang.Object clientId_;
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     * an uuid string
     * </pre>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     * an uuid string
     * </pre>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     * an uuid string
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQID_FIELD_NUMBER = 3;
    private long seqId_;
    /**
     * <code>required int64 seqId = 3;</code>
     */
    public boolean hasSeqId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 seqId = 3;</code>
     */
    public long getSeqId() {
      return seqId_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private com.yflog.lckmgr.msg.LSMessage.Status status_;
    /**
     * <code>optional .com.yflog.lckmgr.msg.Status status = 4;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.yflog.lckmgr.msg.Status status = 4;</code>
     */
    public com.yflog.lckmgr.msg.LSMessage.Status getStatus() {
      return status_;
    }

    public static final int ERRMSG_FIELD_NUMBER = 5;
    private java.lang.Object errmsg_;
    /**
     * <code>optional string errmsg = 5;</code>
     */
    public boolean hasErrmsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string errmsg = 5;</code>
     */
    public java.lang.String getErrmsg() {
      java.lang.Object ref = errmsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errmsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errmsg = 5;</code>
     */
    public com.google.protobuf.ByteString
        getErrmsgBytes() {
      java.lang.Object ref = errmsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LCKNAME_FIELD_NUMBER = 6;
    private java.lang.Object lckName_;
    /**
     * <code>optional string lckName = 6;</code>
     */
    public boolean hasLckName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string lckName = 6;</code>
     */
    public java.lang.String getLckName() {
      java.lang.Object ref = lckName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lckName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lckName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLckNameBytes() {
      java.lang.Object ref = lckName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lckName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      command_ = com.yflog.lckmgr.msg.LSMessage.Message.Command.ACQUIRE;
      clientId_ = "";
      seqId_ = 0L;
      status_ = com.yflog.lckmgr.msg.LSMessage.Status.OK;
      errmsg_ = "";
      lckName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeqId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, command_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, seqId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, status_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getErrmsgBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getLckNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, seqId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getErrmsgBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getLckNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yflog.lckmgr.msg.LSMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yflog.lckmgr.msg.LSMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yflog.lckmgr.msg.LSMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yflog.lckmgr.msg.LSMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yflog.lckmgr.msg.LSMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yflog.lckmgr.msg.LSMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yflog.lckmgr.msg.LSMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yflog.lckmgr.msg.LSMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yflog.lckmgr.msg.LSMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yflog.lckmgr.msg.LSMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yflog.lckmgr.msg.LSMessage.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yflog.lckmgr.msg.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yflog.lckmgr.msg.Message)
        com.yflog.lckmgr.msg.LSMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yflog.lckmgr.msg.LSMessage.internal_static_com_yflog_lckmgr_msg_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yflog.lckmgr.msg.LSMessage.internal_static_com_yflog_lckmgr_msg_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yflog.lckmgr.msg.LSMessage.Message.class, com.yflog.lckmgr.msg.LSMessage.Message.Builder.class);
      }

      // Construct using com.yflog.lckmgr.msg.LSMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        command_ = com.yflog.lckmgr.msg.LSMessage.Message.Command.ACQUIRE;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        seqId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = com.yflog.lckmgr.msg.LSMessage.Status.OK;
        bitField0_ = (bitField0_ & ~0x00000008);
        errmsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        lckName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yflog.lckmgr.msg.LSMessage.internal_static_com_yflog_lckmgr_msg_Message_descriptor;
      }

      public com.yflog.lckmgr.msg.LSMessage.Message getDefaultInstanceForType() {
        return com.yflog.lckmgr.msg.LSMessage.Message.getDefaultInstance();
      }

      public com.yflog.lckmgr.msg.LSMessage.Message build() {
        com.yflog.lckmgr.msg.LSMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yflog.lckmgr.msg.LSMessage.Message buildPartial() {
        com.yflog.lckmgr.msg.LSMessage.Message result = new com.yflog.lckmgr.msg.LSMessage.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.seqId_ = seqId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.errmsg_ = errmsg_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.lckName_ = lckName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yflog.lckmgr.msg.LSMessage.Message) {
          return mergeFrom((com.yflog.lckmgr.msg.LSMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yflog.lckmgr.msg.LSMessage.Message other) {
        if (other == com.yflog.lckmgr.msg.LSMessage.Message.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasClientId()) {
          bitField0_ |= 0x00000002;
          clientId_ = other.clientId_;
          onChanged();
        }
        if (other.hasSeqId()) {
          setSeqId(other.getSeqId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasErrmsg()) {
          bitField0_ |= 0x00000010;
          errmsg_ = other.errmsg_;
          onChanged();
        }
        if (other.hasLckName()) {
          bitField0_ |= 0x00000020;
          lckName_ = other.lckName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasClientId()) {
          
          return false;
        }
        if (!hasSeqId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yflog.lckmgr.msg.LSMessage.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yflog.lckmgr.msg.LSMessage.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yflog.lckmgr.msg.LSMessage.Message.Command command_ = com.yflog.lckmgr.msg.LSMessage.Message.Command.ACQUIRE;
      /**
       * <code>required .com.yflog.lckmgr.msg.Message.Command command = 1 [default = ACQUIRE];</code>
       *
       * <pre>
       * header part
       * </pre>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.yflog.lckmgr.msg.Message.Command command = 1 [default = ACQUIRE];</code>
       *
       * <pre>
       * header part
       * </pre>
       */
      public com.yflog.lckmgr.msg.LSMessage.Message.Command getCommand() {
        return command_;
      }
      /**
       * <code>required .com.yflog.lckmgr.msg.Message.Command command = 1 [default = ACQUIRE];</code>
       *
       * <pre>
       * header part
       * </pre>
       */
      public Builder setCommand(com.yflog.lckmgr.msg.LSMessage.Message.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.yflog.lckmgr.msg.Message.Command command = 1 [default = ACQUIRE];</code>
       *
       * <pre>
       * header part
       * </pre>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = com.yflog.lckmgr.msg.LSMessage.Message.Command.ACQUIRE;
        onChanged();
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>required string clientId = 2;</code>
       *
       * <pre>
       * an uuid string
       * </pre>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string clientId = 2;</code>
       *
       * <pre>
       * an uuid string
       * </pre>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string clientId = 2;</code>
       *
       * <pre>
       * an uuid string
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string clientId = 2;</code>
       *
       * <pre>
       * an uuid string
       * </pre>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string clientId = 2;</code>
       *
       * <pre>
       * an uuid string
       * </pre>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>required string clientId = 2;</code>
       *
       * <pre>
       * an uuid string
       * </pre>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
        return this;
      }

      private long seqId_ ;
      /**
       * <code>required int64 seqId = 3;</code>
       */
      public boolean hasSeqId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 seqId = 3;</code>
       */
      public long getSeqId() {
        return seqId_;
      }
      /**
       * <code>required int64 seqId = 3;</code>
       */
      public Builder setSeqId(long value) {
        bitField0_ |= 0x00000004;
        seqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 seqId = 3;</code>
       */
      public Builder clearSeqId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seqId_ = 0L;
        onChanged();
        return this;
      }

      private com.yflog.lckmgr.msg.LSMessage.Status status_ = com.yflog.lckmgr.msg.LSMessage.Status.OK;
      /**
       * <code>optional .com.yflog.lckmgr.msg.Status status = 4;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.yflog.lckmgr.msg.Status status = 4;</code>
       */
      public com.yflog.lckmgr.msg.LSMessage.Status getStatus() {
        return status_;
      }
      /**
       * <code>optional .com.yflog.lckmgr.msg.Status status = 4;</code>
       */
      public Builder setStatus(com.yflog.lckmgr.msg.LSMessage.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.yflog.lckmgr.msg.Status status = 4;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = com.yflog.lckmgr.msg.LSMessage.Status.OK;
        onChanged();
        return this;
      }

      private java.lang.Object errmsg_ = "";
      /**
       * <code>optional string errmsg = 5;</code>
       */
      public boolean hasErrmsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string errmsg = 5;</code>
       */
      public java.lang.String getErrmsg() {
        java.lang.Object ref = errmsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errmsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errmsg = 5;</code>
       */
      public com.google.protobuf.ByteString
          getErrmsgBytes() {
        java.lang.Object ref = errmsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errmsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errmsg = 5;</code>
       */
      public Builder setErrmsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errmsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errmsg = 5;</code>
       */
      public Builder clearErrmsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errmsg_ = getDefaultInstance().getErrmsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errmsg = 5;</code>
       */
      public Builder setErrmsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errmsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lckName_ = "";
      /**
       * <code>optional string lckName = 6;</code>
       */
      public boolean hasLckName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string lckName = 6;</code>
       */
      public java.lang.String getLckName() {
        java.lang.Object ref = lckName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lckName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lckName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getLckNameBytes() {
        java.lang.Object ref = lckName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lckName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lckName = 6;</code>
       */
      public Builder setLckName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        lckName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lckName = 6;</code>
       */
      public Builder clearLckName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        lckName_ = getDefaultInstance().getLckName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lckName = 6;</code>
       */
      public Builder setLckNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        lckName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.yflog.lckmgr.msg.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.yflog.lckmgr.msg.Message)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yflog_lckmgr_msg_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yflog_lckmgr_msg_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\024com.yflog.lckmgr.msg\"\337\001" +
      "\n\007Message\022?\n\007command\030\001 \002(\0162%.com.yflog.l" +
      "ckmgr.msg.Message.Command:\007ACQUIRE\022\020\n\010cl" +
      "ientId\030\002 \002(\t\022\r\n\005seqId\030\003 \002(\003\022,\n\006status\030\004 " +
      "\001(\0162\034.com.yflog.lckmgr.msg.Status\022\016\n\006err" +
      "msg\030\005 \001(\t\022\017\n\007lckName\030\006 \001(\t\"#\n\007Command\022\013\n" +
      "\007ACQUIRE\020\001\022\013\n\007RELEASE\020\002*W\n\006Status\022\006\n\002OK\020" +
      "\001\022\020\n\014INVALID_LOCK\020\002\022\014\n\010TIME_OUT\020\003\022\021\n\rCLI" +
      "ENT_CLOSED\020\004\022\022\n\016NOT_LOCK_OWNER\020\006B\rB\tLSMe" +
      "ssageH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yflog_lckmgr_msg_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yflog_lckmgr_msg_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_yflog_lckmgr_msg_Message_descriptor,
        new java.lang.String[] { "Command", "ClientId", "SeqId", "Status", "Errmsg", "LckName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
